### ISSUE TITLE
Server app crashing

### ISSUE THREAD

**Issue by osamabinsaleem** [zoom/meetingsdk-web-bot-sample#1]
I'm getting this error: 
```
/Users/osamabinsaleem/Desktop/NativeVideo/development/meetingsdk-web-bot-sample/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28
        throw new Error(message);
              ^

Error: No element found for selector: button
    at assert (/Users/osamabinsaleem/Desktop/NativeVideo/development/meetingsdk-web-bot-sample/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28:15)
    at IsolatedWorld.click (/Users/osamabinsaleem/Desktop/NativeVideo/development/meetingsdk-web-bot-sample/node_modules/puppeteer-core/lib/cjs/puppeteer/common/IsolatedWorld.js:190:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async clickJoinMeetingButton (/Users/osamabinsaleem/Desktop/NativeVideo/development/meetingsdk-web-bot-sample/backend/helpers/meetingBot.js:27:3)

Node.js v18.14.0
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by osamabinsaleem** [comment]
in the Readme, it's not very clear with which url should I replace it with? I tried with the meeting url and it is not working.
```await page.goto("{Enter local development url or site url}", {
    waitUntil: "load",


  });
```

**Comment by Debabrata47** [comment]
1.U need set the url which the index.html open up in local pc!
2.Other than that make sure to set up all the creditionals in .env file
3.npm install in just root folder
